
```{r}

### Load data and set up the environment
setwd("/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/statisic")

# Define paths to the data files and the script
pathbig <- "/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/statisic/uncenter/adjstats0004300.RData"
pathmedian <- "/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/statisic/uncenter/adjstats9599300.RData"
pathsmall <- "/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/statisic/uncenter/adjstats9094300.RData"
source("/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/statisic/leg.R")
pathplot <- "/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/statisic/plot200"


# Load necessary libraries for data visualization
library(ggExtra)
library(ggplot2)
library(scales)
library(RColorBrewer)

# Define a custom color palette for plots
colorManual <- c("#377EB8","#A50F15", "#FF7F00")
col<-c("#66C2A5","#377EB8","#FF7F00")

# Define a scaling factor
k <- 2
temp <- k*100

# Load and process the 00-04 dataset
load(pathbig)
df1 <- as.data.frame(resexa[[k]])[1:2000,1:3]
df1 <- df1*sqrt(temp)/sqrt(temp*(1 - temp/750))

# Load and process the 95-99 dataset
load(pathmedian)
df2 <- as.data.frame(resexa[[k]])[1:2000,1:3]
df2 <- df2*sqrt(temp)/sqrt(temp*(1 - temp/750))

# Load and process the 90-94 dataset
load(pathsmall)
df3 <- as.data.frame(resexa[[k]])[1:2000,1:3]
df3 <- df3*sqrt(temp)/sqrt(temp*(1 - temp/600))


```

```{r}
# Define theme settings for ggplot2 plots
as <- 50
bs <- 25
mytheme<-  theme_bw() +
  theme(
    text = element_text(size = as),
    axis.text.x = element_text(size = bs),  # Adjust the size of x-axis labels
    axis.text.y = element_text(size = bs)   # Adjust the size of y-axis labels
  ) 

mytheme2<-mytheme+theme(panel.grid=element_blank())



# Set the working directory for saving plots
setwd("/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/stats/plot200")


```

```{r}
# Set the spacing parameter
space <- 2

# Add a time period column to each dataframe
df1$timeperiod <- "2000-2004"
df2$timeperiod <- "1995-1999"
df3$timeperiod <-  "1990-1994"


# Combine the three dataframes into one
combined_df <- rbind(df1, df2, df3)


# Create the plot
p11 <- ggplot(combined_df, aes(x = combined_df[,1], y = combined_df[,2], color = timeperiod,alpha =timeperiod )) +
  geom_point() +
  labs(x='2-star',y='Triangle',col='Period')+
  theme_minimal() +
  mytheme+
  theme(axis.title.x = element_text(size = 30,
                                    margin = margin(t = 10, b = -5)
  ),
  axis.title.y = element_text(size = 30,
                              margin = margin(t = 10, b = -5)
  )
  )+
  coord_cartesian(clip='off')+
  scale_y_continuous(breaks=c(0,10000,20000,30000),labels =\(x) sprintf('%4.1f',x/10000) )+
  scale_color_manual(values =col)+
  scale_alpha_manual(values = c(0.8,0.4,0.4))+
  guides(color = guide_legend(override.aes = list(alpha = 1,
                                                  size = 3)),
         alpha = "none"
  ) +
  theme(panel.border = element_rect(linetype = "solid",fill = NA,linewidth =0.5), 
        plot.margin=unit(c(0.5,0.5,0.5,0.5),units=,"cm"),
        legend.title = element_text(size = bs),
        # legend.key=element_blank(),  
        legend.text = element_text(color="black",size=bs), 
        legend.spacing.x=unit(0,'cm'), 
        legend.background=element_blank(), 
        legend.box.background=element_rect(colour = "black"), 
        legend.box.margin = margin(1,1,1,1),
        legend.position = c(0.58,1),  
        legend.justification = c(0,1))

ggMarginal(p11, type = "density", groupColour = TRUE
           , groupFill = TRUE,alpha = 0.7#,size = 2
           ,xparams = list( size = 0.8)
           ,yparams = list( size = 0.8)
)

ggsave('out_v_tri.pdf',width=7.7,height=6)
grid.draw(p11)
dev.off()

```

```{r}

# Create the plot
combined_df2<-combined_df[combined_df$timeperiod!='1990-1994',]
p21 <- ggplot(combined_df2, aes(x = combined_df2[,1], y = combined_df2[,2], color = timeperiod,alpha =timeperiod )) +
  geom_point() +
  labs(x='2-star',y='Triangle',col='Period')+
  theme_minimal() +
  mytheme+
  theme(axis.title.x = element_text(size = 30,
                                    margin = margin(t = 10, b = -5)
  ),
  axis.title.y = element_text(size = 30,
                              margin = margin(t = 10, b = -5)
  )
  )+
  coord_cartesian(clip='off')+
  #  scale_x_continuous(breaks = c(-50,25,100,175),
  #                 labels = c(-50,25,100,175)) + 
  scale_y_continuous(breaks=c(0,10000,20000,30000),labels =\(x) sprintf('%4.1f',x/10000) )+
  scale_color_manual(values =c("#377EB8","#FF7F00"))+
  scale_alpha_manual(values = c(0.4,0.4))+
  guides(color = guide_legend(override.aes = list(alpha = 1,
                                                  size = 3)),
         alpha = "none"
  ) +
  theme(panel.border = element_rect(linetype = "solid",fill = NA,linewidth =0.5), 
        plot.margin=unit(c(0.5,0.5,0.5,0.5),units=,"cm"),
        legend.title = element_text(size = bs),
        # legend.key=element_blank(),   
        legend.text = element_text(color="black",size=bs), 
        legend.spacing.x=unit(0,'cm'), 
        legend.background=element_blank(), 
        legend.box.background=element_rect(colour = "black"), 
        legend.box.margin = margin(1,1,1,1),
        legend.position = c(0.58,1),  
        legend.justification = c(0,1))


ggMarginal(p21, type = "density", groupColour = TRUE
           , groupFill = TRUE,alpha = 0.7#,size = 2
           ,xparams = list( size = 0.8)
           ,yparams = list( size = 0.8)
)

```

```{r}
# Create the plot
p12 <- ggplot(combined_df, aes(x = combined_df[,1], y = combined_df[,3], color = timeperiod,alpha = timeperiod)) +
  geom_point() +
  labs(x='2-star',y='3-star',col='Period')+
  theme_minimal() +
  theme_bw() +
  theme(
    panel.border = element_rect(linetype = "solid",fill = NA,linewidth =0.5), 
    plot.margin=unit(c(0.5,0.5,0.5,0.5),units=,"cm"),
    legend.title = element_text(size = bs),
    legend.text = element_text(color="black",size=bs), 
    legend.spacing.x=unit(0,'cm'), 
    legend.background=element_blank(), 
    legend.box.background=element_rect(colour = "black"), 
    legend.box.margin = margin(1,1,1,1),
    legend.position = c(0,1),  
    legend.justification = c(0,1),
    axis.title.x = element_text(size = 30,
                                margin = margin(t = 10, b = -5)
    ),
    axis.title.y = element_text(size = 30,
                                margin = margin(t = 10, b = -5)
    ),
    axis.text.x = element_text(size = bs),  # Adjust the size of x-axis labels
    axis.text.y = element_text(size = bs)   # Adjust the size of y-axis labels
  ) +
  coord_cartesian(clip='off'
                  # ,xlim = c(-50, 200)
  )+
  scale_y_continuous(breaks=c(0,1200,2400,3600),labels =\(x) sprintf('%4.1f',x/1000) )+
  scale_color_manual(values =col)+
  scale_alpha_manual(values = c(0.8,0.4,0.4))+
  guides(color = guide_legend(override.aes = list(alpha = 1,
                                                  size = 3)),
         alpha = "none"
  )


ggMarginal(p12, type = "density", groupColour = TRUE
           , groupFill = TRUE,alpha = 0.7#,size = 2
           ,xparams = list( size = 0.8)
           ,yparams = list( size = 0.8)
)

ggsave('out_v_3.pdf',width=7.7,height=6)
grid.draw(p12)
dev.off()

```


```{r}
# Create the plot
p22 <- ggplot(combined_df2, aes(x = combined_df2[,1], y = combined_df2[,3], color = timeperiod,alpha = timeperiod)) +
  geom_point() +
  labs(x='2-star',y='3-star',col='Period')+
  theme_minimal() +
  theme_bw() +
  theme(
    panel.border = element_rect(linetype = "solid",fill = NA,linewidth =0.5), 
    plot.margin=unit(c(0.5,0.5,0.5,0.5),units=,"cm"),
    legend.title = element_text(size = bs),
    legend.text = element_text(color="black",size=bs), 
    legend.spacing.x=unit(0,'cm'), 
    legend.background=element_blank(), 
    legend.box.background=element_rect(colour = "black"), 
    legend.box.margin = margin(1,1,1,1),
    legend.position = c(0,1),   
    legend.justification = c(0,1),
    axis.title.x = element_text(size = 30,
                                margin = margin(t = 10, b = -5)
    ),
    axis.title.y = element_text(size = 30,
                                margin = margin(t = 10, b = -5)
    ),
    axis.text.x = element_text(size = bs),  # Adjust the size of x-axis labels
    axis.text.y = element_text(size = bs)   # Adjust the size of y-axis labels
  ) +
  coord_cartesian(clip='off'
                  # ,xlim = c(-50, 200)
  )+
  scale_y_continuous(breaks=c(0,1200,2400,3600),labels =\(x) sprintf('%4.1f',x/1000) )+
  scale_color_manual(values =c("#377EB8","#FF7F00"))+
  scale_alpha_manual(values = c(0.8,0.4,0.4))+
  guides(color = guide_legend(override.aes = list(alpha = 1,
                                                  size = 3)),
         alpha = "none"
  ) 

ggMarginal(p22, type = "density", groupColour = TRUE
           , groupFill = TRUE,alpha = 0.7#,size = 2
           ,xparams = list( size = 0.8)
           ,yparams = list( size = 0.8)
)

ggsave('out_v_2.pdf',width=7.7,height=6)
grid.draw(p22)
dev.off()
```

