```{r}
# Load necessary libraries for data visualization and color management

library(ggplot2)
library(RColorBrewer)
library(scales)
library(gggrid)
library(ggside)



# Define a custom color palette to be used in the plots
colorManual <- c("#377EB8", "#FF7F00", "#984EA3" ,"#4DAF4A", "#F781BF", "#A65628" )


# Set the corresponding directory to the specified path where data and scripts are stored
setwd("/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/guppy")

# Source an external R script (leg.R) for additional functions or data processing
source("/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/guppy/leg.R")

# Load a saved R data
load("/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/guppy/guppylc.RData")
load("/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/guppy/URG.RData")




# Set a variable 'space' to a value of 2 (This might be used later in the code)
space<-2 


```

```{r}


# Load necessary data and scripts, set up environment
res <- res_guppy
exact <- res[[2]]
exactdf <- exact[[2]]
n <- dim(guppylarge)[[1]]


# Calculate and adjust network statistics
UR_G <- UR_G$UR_exact
rho_hat_GG <- sum(guppylarge)/(n*(n-1))
rho_hat_GG_UR_G <- UR_G*c(rho_hat_GG^(-2),rho_hat_GG^(-3),rho_hat_GG^(-3),rho_hat_GG^(-4))
sqrtbrho_hat_GG_UR_G <- sqrt(618)*rho_hat_GG_UR_G
smallNetMoment <-  exact[[1]]
tau <- sqrt(1 - (618/16485))
smallNetMoment  <-  smallNetMoment*tau 
names(smallNetMoment) <- c("twoStar","triangle","threeStar","square")



# Define plot themes and settings
as <- 50
bs <- 25
cs <- 1.5
mytheme<-  theme_bw() +
  theme(
    text = element_text(size = as),
    #panel.grid=element_blank(),
    legend.position = "none",
    plot.title = element_text(size = bs),
    axis.text.x = element_text(size = bs),  # Adjust the size of x-axis labels
    axis.text.y = element_text(size = bs)   # Adjust the size of y-axis labels
  ) 
  
mytheme2<-mytheme+theme(panel.grid=element_blank())


# Extract and plot specific network statistics
v_stats <-  smallNetMoment[1]
tri_stats <-  smallNetMoment[2]
tstar_stats <-  smallNetMoment[3]
square_stats <-  smallNetMoment[4]
exadf <- as.data.frame(exact[[2]][1:2000,])


# Create and save the plots
df <- data.frame(x = exadf$twoStar, y = exadf$triangle)
p11 <-ggplot(exadf) + 
     geom_point(aes(x = twoStar, y = triangle),alpha=0.1, colour=colorManual[1]) +   
     stat_density2d(aes(x = twoStar, y = triangle), colour=colorManual[2]) +  
     geom_hline(yintercept = tri_stats, linetype = 'dashed', color = 'black', size = 0.6) +
     geom_vline(xintercept = v_stats, linetype = 'dashed', color = 'black', size = 0.6) +  
     geom_point(x = v_stats, y =  tri_stats, color = "#E41A1C", size = 3) +
      mytheme+
	  coord_cartesian(clip='off')+
     scale_x_continuous(breaks=c(70, 140,210,280)
                         # ,labels =\(x) sprintf('%4.1f',x/100) 
                        ) +  # Use scientific notation for x-axis
     scale_y_continuous(breaks=c(2500,5000,7500),labels =\(x) sprintf('%4.1f',x/1000) )+
      theme(axis.title.x = element_text(size = 30,hjust = 0.35,
                                        margin = margin(t = 10, b = -5)
                                        ),
            axis.title.y = element_text(size = 30,hjust = 0.35,
                                        margin = margin(t = 10, b = -5)
                                        ),
            axis.text.x = element_text(color = "black"),
            axis.text.y = element_text(color = "black"),
            aspect.ratio = 1, 
            ggside.panel.border = element_blank(),
            ggside.panel.grid = element_blank(),
            ggside.panel.background = element_blank(),
            ggside.axis.text = element_blank(),
            ggside.axis.ticks = element_blank(),
            ggside.panel.scale = .3
        )+
  xlab("2-star")+
  ylab("Triangle")+
  geom_xsidedensity(aes(x = twoStar),
                    ,color = colorManual[1]
                    ,fill=colorManual[1],alpha = 0.65,size = 0.8) +
  geom_ysidedensity(aes(y = triangle),
                    ,color = colorManual[1]
                    ,fill=colorManual[1],alpha = 0.65,size = 0.8
                    ) +
  geom_xsidevline(xintercept = v_stats,linetype = 'dashed', color = 'black', size = 0.6) +
  geom_ysidehline(yintercept = tri_stats,linetype = 'dashed', color = 'black', size = 0.6) 
pdf('out_v_tri.pdf',width=7.7,height=6)
grid.draw(p11)
dev.off()
 


p12<-ggplot(exadf) + 
     geom_point(aes(x = twoStar, y = threeStar),alpha=0.1, colour=colorManual[1]) +   
     stat_density2d(aes(x = twoStar, y = threeStar), colour=colorManual[2]) +  
     geom_hline(yintercept = tstar_stats, linetype = 'dashed', color = 'black', size = 0.6) +
     geom_vline(xintercept = v_stats, linetype = 'dashed', color = 'black', size = 0.6) +  
     geom_point(x = v_stats, y = tstar_stats, color = "#E41A1C", size = 3) +
      mytheme+
	  coord_cartesian(clip='off')+
     scale_x_continuous(breaks=c(0, 70, 140,210,280)
                        ,labels =c(0, 70, 140,210,280)
                         # ,labels =\(x) sprintf('%4.1f',x/100) 
                        ) +  # Use scientific notation for x-axis
     scale_y_continuous(breaks=c(0,250,500,750,1000),labels =\(x) sprintf('%4.1f',x/100) )+
      theme(axis.title.x = element_text(size = 30,hjust = 0.35,
                                        margin = margin(t = 10, b = -5)
                                        ),
            axis.title.y = element_text(size = 30,hjust = 0.35,
                                        margin = margin(t = 10, b = -5)
                                        ),
            axis.text.x = element_text(color = "black"),
            axis.text.y = element_text(color = "black"),
            aspect.ratio = 1, 
            ggside.panel.border = element_blank(),
            ggside.panel.grid = element_blank(),
            ggside.panel.background = element_blank(),
            ggside.axis.text = element_blank(),
            ggside.axis.ticks = element_blank(),
            ggside.panel.scale = .3
        )+
  xlab("2-star")+
  ylab("3-star")+
  geom_xsidedensity(aes(x = twoStar),
                    ,color = colorManual[1]
                    ,fill=colorManual[1],alpha = 0.65,size = 0.8) +
  geom_ysidedensity(aes(y = threeStar),
                    ,color = colorManual[1]
                    ,fill=colorManual[1],alpha = 0.65,size = 0.8
                    ) +
  geom_xsidevline(xintercept = v_stats,linetype = 'dashed', color = 'black', size = 0.6) +
  geom_ysidehline(yintercept = tstar_stats,linetype = 'dashed', color = 'black', size = 0.6) 
	  
pdf('out_v_3.pdf',width=7.7,height=6)
grid.draw(p12)
dev.off()
 


p13<- ggplot(exadf) + 
     geom_point(aes(x = triangle, y = threeStar),alpha=0.1, colour=colorManual[1]) +   
     stat_density2d(aes(x = triangle, y = threeStar), colour=colorManual[2]) +  
     geom_hline(yintercept = tstar_stats, linetype = 'dashed', color = 'black', size = 0.6) +
     geom_vline(xintercept = tri_stats, linetype = 'dashed', color = 'black', size = 0.6) +  
     geom_point(x = tri_stats, y = tstar_stats, color = "#E41A1C", size = 3) +
      mytheme+
	  coord_cartesian(clip='off')+
     scale_x_continuous(breaks=c(2000,4000,6000,8000),labels =\(x) sprintf('%4.1f',x/1000) )+
      scale_y_continuous(breaks=c(250,500,750,1000),labels =\(x) sprintf('%4.1f',x/100) )+
      theme(axis.title.x = element_text(size = 30,hjust = 0.35,
                                        margin = margin(t = 10, b = -5)
                                        ),
            axis.title.y = element_text(size = 30,hjust = 0.35,
                                        margin = margin(t = 10, b = -5)
                                        ),
            axis.text.x = element_text(color = "black"),
            axis.text.y = element_text(color = "black"),
            aspect.ratio = 1,  
            ggside.panel.border = element_blank(),
            ggside.panel.grid = element_blank(),
            ggside.panel.background = element_blank(),
            ggside.axis.text = element_blank(),
            ggside.axis.ticks = element_blank(),
            ggside.panel.scale = .3
        )+
  xlab("Triangle")+
  ylab("3-star")+
  geom_xsidedensity(aes(x = triangle),
                    ,color = colorManual[1]
                    ,fill=colorManual[1],alpha = 0.65,size = 0.8) +
  geom_ysidedensity(aes(y = threeStar),
                    ,color = colorManual[1]
                    ,fill=colorManual[1],alpha = 0.65,size = 0.8
                    ) +
  geom_xsidevline(xintercept = tri_stats,linetype = 'dashed', color = 'black', size = 0.6) +
  geom_ysidehline(yintercept = tstar_stats,linetype = 'dashed', color = 'black', size = 0.6) 


pdf('out_tri_tstar.pdf',width=7.7,height=6)
grid.draw(p13)
dev.off()
############
```

```{r}
##### Density calculation and plotting

# Set up the environment and load the necessary data
res <- res_guppy
exact <- res[[2]]
exadf <- as.data.frame(exact[[2]])

# Calculate the number of three-star structures that are less than or equal to 'tstar_stats'
sum(exadf$threeStar <= tstar_stats)



# Calculate the quantile of the specific value
quantile_of_value <- (sum(exadf$threeStar <= tstar_stats)) / length(exadf$threeStar)


# Create and customize a histogram plot for three-star structures
pd11<-ggplot(exadf, aes(x = threeStar)) +  ###threestar_mar.pdf
      geom_histogram(bins = 30, fill = colorManual[1], color = "black") + # Adjust the number of bins as needed
      geom_vline(aes(xintercept = tstar_stats), color = "red", linetype = "dashed") + 
      mytheme2+
      #labs(x = "three star", y = "density",title="quantile: 0.588")+
      labs(x = "three star", y = "density",title=paste("percentile:", round(quantile_of_value,3)))+
	  mytheme2+
      grid_panel(textGrob(y=unit(-0.1,'lines'),x=1,just=c('right','top'),label='X1000',gp=gpar(cex=cs )))+
	  grid_panel(textGrob(y=1,x=unit(-0.1,'lines'),just=c('right','top'),label='X1000',gp=gpar(cex=cs )))+
	  coord_cartesian(clip='off')+
      scale_x_continuous(breaks=c(-300, 0, 300, 600),labels =\(x) sprintf('%4.1f',x/1000) ) +  # Use scientific notation for x-axis
      scale_y_continuous(breaks=c(0,500,1000),labels =\(x) sprintf('%4.1f',x/1000),expand=expansion(c(0,0.05)))


ggplotGrob(pd11)->pd11g
pd11g$grobs[[12]]<-v3
pd11g$heights[10]<-unit(space,'cm')
pd11g$widths[6]<-unit(space,'cm')
pdf('out_threestar_mar.pdf',width=7.7,height=6)
grid.draw(pd11g)
dev.off()


# Calculate the quantile of the specific value
quantile_of_value <- sum(exadf$twoStar <= v_stats) / length(exadf$threeStar)

pd12<-ggplot(exadf, aes(x = twoStar)) +  ###twostar_mar.pdf
       geom_histogram(bins = 20, fill = colorManual[1], alpha = 0.65, color = "black") + # Adjust the number of bins as needed
       geom_vline(aes(xintercept = v_stats), color = "red", linetype = "dashed") + 
       mytheme2+
       #labs(x = "three star", y = "density",title="quantile: 0.333")+
       labs(x = "three star", y = "density",title=paste("percentile:", round(quantile_of_value,3)))+
	   mytheme2+
      grid_panel(textGrob(y=unit(-0.1,'lines'),x=1,just=c('right','top'),label='X100',gp=gpar(cex=cs )))+
	  grid_panel(textGrob(y=1,x=unit(-0.1,'lines'),just=c('right','top'),label='X1000',gp=gpar(cex=cs )))+
	  coord_cartesian(clip='off')+
      scale_x_continuous(breaks=c(-80, -10, 60, 130 ),labels =\(x) sprintf('%4.1f',x/100) ) +  # Use scientific notation for x-axis
      scale_y_continuous(breaks=c(0,500,1000,1500),labels =\(x) sprintf('%4.1f',x/1000),expand=expansion(c(0,0.05)))


ggplotGrob(pd12)->pd12g
pd12g$grobs[[12]]<-v1

pd12g$heights[10]<-unit(space,'cm')
pd12g$widths[6]<-unit(space,'cm')


pdf('out_twostar_mar.pdf',width=7.7,height=6)
grid.draw(pd12g)
dev.off()



point <- c(v_stats, tstar_stats)
a <- 0.95*v_stats
b <- 1.05*v_stats
df <- exadf[,c(1,3)]
temp <- df[which((df$twoStar > a) & (df$twoStar < b)),]

# Calculate the quantile of the specific value
quantile_of_value <- sum(temp$threeStar<= tstar_stats) / length(temp$threeStar)


pd13<-ggplot(temp, aes(x = threeStar,y=..density..)) +
  
  geom_histogram(bins = 11, fill = colorManual[1],alpha=0.65, color = "black") + # Adjust the number of bins as needed
  #geom_density(color = colorManual[2],size =0.75)+
  # geom_density(fill = colorManual[1], color = "black",alpha=0.65)+
  geom_vline(aes(xintercept = tstar_stats), color = "red", linetype = "dashed",size =3) + 
	  
  mytheme2+
  labs(x = "3-star | 2-star",y = ""
       ,title=paste("Percentile:", round(quantile_of_value,3)))+
  theme(axis.title.x = element_text(size = 30,hjust = 0.5,
                                    margin = margin(t = 10, b = -5)
                                    )
        # ,axis.text.y = element_blank()
        # ,axis.ticks.y = element_blank()
        )+
  # theme(plot.title = element_text(hjust = 0.5))+
#       grid_panel(textGrob(y=unit(-0.1,'lines'),x=1,just=c('right','top'),label='X100',gp=gpar(cex=cs)))+
# 	  grid_panel(textGrob(y=1,x=unit(-0.1,'lines'),just=c('right','top'),label='X10',gp=gpar(cex=cs)))+
	  coord_cartesian(clip='off')+
     # scale_x_continuous(breaks=c(-265, -240, -215, -190)
                         # ,labels =\(x) sprintf('%4.1f',x/100)
      #                   ,labels = c(-260, -240, -220, -200)
       #                  ) +
 # scale_y_continuous( breaks = seq(0,0.03,0.01)
  #                  ,limits= c(0,0.03)
   #                 ,labels = c(0.0,0.1,0.2,0.3 )
    #               )
  



pdf('out_threeontwo_cond.pdf',width=7.7,height=6)
grid.draw(pd13)
dev.off()

```
